services:
  - type: static_site
    name: angular-frontend-eng
    branch: master
    buildCommand: npm install && npx nx build angular-frontend --configuration=eng
    staticPublishPath: dist/angular-frontend

  - type: static_site
    name: angular-frontend-test
    branch: master
    buildCommand: npm install && npx nx build angular-frontend --configuration=test
    staticPublishPath: dist/angular-frontend

  - type: static_site
    name: angular-frontend-prod
    branch: master
    buildCommand: npm install && npx nx build angular-frontend --configuration=production
    staticPublishPath: dist/angular-frontend
