name: Build and Deploy Angular UI Application

on:
  push:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  CI-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Unit Tests
        run: npm run test

  deploy-eng:
    needs: CI-runs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build ENG
        run: npm run build:eng

      - name: Deploy to ENG GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.DEPLOY_SECRET }}
          publish_dir: ./dist/eng
          external_repository: nbshankar/nbshankar-angular-ui-eng.github.io
          publish_branch: master

  deploy-prod:
    needs: deploy-eng
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build PROD
        run: npm run build:prod

      - name: Deploy to PROD GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.DEPLOY_SECRET }}
          publish_dir: ./dist/prod
          external_repository: nbshankar/nbshankar-angular-ui-prod.github.io
          publish_branch: master
